- name: FirstTests
  hosts: 
  tasks: 
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print result
      ansible.builtin.debug:
        msg: hello world
    - include_tasks: cmd.yml
