- name: FirstTests
  hosts: local
    role: 
      - common
  tasks: 
  - name: Show all the hosts in the inventory
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ groups['all'] }}"
  - include_tasks: cmd.yml
